jobs:
  include:
    - stage: flutter test
      name: unit test
      os: linux
      language: generic
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            # - fonts-droid-fallback
      before_script:
        - export TZ=Europe/Berlin
        - chmod +x .travis/before_script.sh
        - chmod +x .travis/test.sh
        - source .travis/before_script.sh
      script:
        - .travis/test.sh
cache:
  directories:
    - $HOME/.pub-cache
