name: mixpanel_analytics
description: A dart wrapper on the mixpanel REST API to be used in Flutter applications.
As this is using the http REST API it works both with Android and iOS.
version: 1.0.0
author: Alpha Innovation
homepage:
repository:
issue_tracker:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  shared_preferences: ^0.5.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
